services:
  auth_postgres:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth_service
    depends_on:
      - auth_postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth_postgres:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      JWT_SECRET: 9f8bHj2kLmN0pQ5rT7sUvWxYzAbCdEfG
      JWT_EXPIRATION: 86400000
    env_file:
     - .env